version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - 55432:5432
    networks:
      - app-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - app-net
    volumes:
      - ./output:/output
      - ./logs:/logs
      - .env:/.env # /src/.env

volumes:
  pgdata:
  output:
  logs:

networks:
  app-net:
    driver: bridge
